/**
 * 
 */
package ca.gc.dfo.slims.constants;

/**
 * @author ZHUY
 *
 */
public enum RefCodeType
{
	DISCHARGE_CODE("DISCHARGE_CODE"),
	
	MAP_DATUM("MAP_DATUM"),
	
	OPERATING_UNIT("OPERATING_UNIT"),
	
	OPERATORS("OPERATORS"),
	
	UTM_ZONE("UTM_ZONE"),
	
	UTM_BAND("UTM_BAND"),
	
	UTM_ZONE_BAND("UTM_ZONE_BAND"),
	
	SURVEY_PURPOSE("SURVEY_PURPOSE"),
	
	SURVEY_METHODOLOGY("SURVEY_METHODOLOGY"),
	
	SPECIMEN_STATE("SPECIMEN_STATE"),
	
	FISH_SEX("SEX"),
		
	HI_MEASUREMENTS("HI_MEASUREMENTS"),
	
	HABITAT_TYPE("HABITAT_TYPE"),
	
	TREATMENT_METHODOLOGY("TREATMENT_METHODOLOGY"),
	
	SL_ABUNDANCE_INDEX("SL_ABUNDANCE_INDEX"),
	
	PRIMARY_APPLICATION_CODE("PRIMARY_APPLICATION_CODE"),
	
	SECONDARY_APPLICATION_CODE("SECONDARY_APPLICATION_CODE"),
	
	PRIMARY_APPLICATION_METHOD("PRIMARY_APPLICATION_METHOD"),
	
	SECONDARY_APPLICATION_METHOD("SECONDARY_APPLICATION_METHOD"),
	
	TFM_PERCAI("TFM_PERCAI"),
	
	WP_PERCAI("WP_PERCAI"),
	
	EC_PERCAI("EC_PERCAI"),
	
	GB_PERCAI("GB_PERCAI"),
	
	ESTIMATE_CODE("ESTIMATE_CODE"),
	
	PREDICTION_CHART("PREDICTION_CHART"),
	
	FLOW_TIME_CODE("FLOW_TIME_CODE"),
	
	METHOD_CODE("METHOD_CODE"),
	
	OPERATING_CODE("OPERATING_CODE"),
	
	TEMP_DEVICE("TEMP_DEVICE"),
	
	GAUGE_TYPE("GAUGE_TYPE"),
	
	TRAP_CHAMBER("TRAP_CHAMBER"),
	
	MATURITY("MATURITY"),
	
	MANAGEMENT_UNIT("MANAGEMENT_UNIT"),
	
	GEAR("GEAR"),
	
	HOST_TYPE("HOST_TYPE"),
	
	GUT_CONDITION("GUT_CONDITION"),
	
	GUT_FULLNESS("GUT_FULLNESS"),
	
	GUT_CONTENTS("GUT_CONTENTS"),
	
	FM_SURVEY_PURPOSE("FM_SURVEY_PURPOSE"),
	
	FM_TECHNIQUE("FM_TECHNIQUE"),
	
	FM_METHODOLOGY("FM_METHODOLOGY");
	
	private final String name;
	
	/**
	 * @return the name
	 */
	public String getName()
	{
		return name;
	}
	
	/**
	 * @param name
	 */
	private RefCodeType(String name)
	{
		this.name = name;
	}
}
